version: 2.1

orbs:
  git: opuscapita/git@volatile
  codecov: codecov/codecov@1.0.5

aliases:
  - &restore_cache
    keys:
      - v1-fsm4j-{{ .Branch }}-{{ checksum "core/pom.xml" }}-{{ checksum "editor/package.json" }}-{{ checksum "history/grails-app/conf/BuildConfig.groovy" }}
      - v1-fsm4j-{{ .Branch }}
      - v1-fsm4j

  - &save_cache
    key: v1-fsm4j-{{ .Branch }}-{{ checksum "core/pom.xml" }}-{{ checksum "editor/package.json" }}-{{ checksum "history/grails-app/conf/BuildConfig.groovy" }}
    paths:
      - ~/.m2/repository
      - editor/node_modules

setup_docker: &setup_docker
  docker:
    - image: opuscapita/fsm4j:ci
      environment:
        JAVA_OPTS: -Xms2g -Xmx2g
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  working_directory: ~/build

jobs:
  init:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: circle_ci_add_env.sh

  build-docker-ci:
    docker:
    - image: docker
    steps:
      - run: apk add --no-cache bash make git openssh-client
      - checkout
      - run: wget -O /vault.zip https://releases.hashicorp.com/vault/1.8.4/vault_1.8.4_linux_amd64.zip; unzip /vault.zip -d /usr/bin/
      - setup_remote_docker
      - run:
          name: Check if image build is required
          command: |
            make docker-auth
            if [ -z "$(git show --name-only | grep build/docker/ci)" ]; then
              DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect opuscapita/fsm4j:ci && \
                circleci step halt || echo "Image doesn't exist, proceed"
            fi
      - run: make build-docker-ci && make publish-docker-ci

  build:
    <<: *setup_docker
    steps:
      - git/checkout-with-submodules
      - restore_cache: *restore_cache
      - run:
          name: "Build, running tests and deploy the artefacts to remote repositories"
          command: if [ ! -z "$CIRCLE_TAG" ]; then make deploy-release; else make deploy; fi
      - setup_remote_docker
      - run:
          name: Build docker image
          command: make build-docker
      - run:
          name: Publish docker image
          command: make publish-docker
      - save_cache: *save_cache
      - codecov/upload:
          flags: unittest
          file: core/target/site/jacoco/*.*
      - run:
          name: 'History-plugin: Save grails test results.'
          command: |
            mkdir -p ~/history/test-xml-reports/
            find . -type f -regex ".*/target/test-reports/.*xml" -exec cp -v {} ~/history/test-xml-reports/ \;
          when: always
          working_directory: ~/build/history
      - store_test_results:
          path: ~/history/test-xml-reports
      - store_artifacts:
          path: ~/history/test-xml-reports
      - run:
          name: 'Core-module: Save maven test results.'
          command: |
            mkdir -p ~/core/test-xml-reports/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp -v {} ~/core/test-xml-reports/ \;
          when: always
          working_directory: ~/build/core
      - store_test_results:
          path: ~/core/test-xml-reports
      - store_artifacts:
          path: ~/core/test-xml-reports
      - run:
          name: Build technical documentation
          command: make doc
      - run:
          name: Publish technical documentation
          command: if [ ! -z "$CIRCLE_TAG" ]; then make doc-publish; fi

  deploy-demo:
    <<: *setup_docker
    steps:
      - git/checkout-with-submodules
      - run:
          name: Build and deploy demo to remote repository
          command: if [ -z "$CIRCLE_TAG" ]; then make deploy-demo CI_BUILD_URL=${CIRCLE_BUILD_URL}; fi

workflows:
  version: 2
  commit:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/
      - build-docker-ci:
          filters:
            tags:
              only: /.*/
          requires:
            - init
      - build:
          filters:
            tags:
              only: /.*/
          requires:
            - init
            - build-docker-ci
      - deploy-demo:
          filters:
            tags:
              only: /.*/
          requires:
            - init
            - build-docker-ci
            - build
